### ISSUE TITLE
Parsing the files

### ISSUE THREAD

**Issue by wenzla** [wenzla/Data-Mining-Project#1]
The first thing we need to do is to parse the data files.

I found this when figuring out how to do it, but I'm not sure it will work (it seems to be part of the standard python 2.7 libraries, so it should work).
https://docs.python.org/2/library/htmlparser.html

**Comment by shraddhasunil** [comment]
I'm thinking of using beautifulsoup to do the parsing. It works quite neatly. Trying to figure out how to use it.

**Comment by wenzla** [comment]
Sounds good but we have to make sure it works on stdlinux

**Comment by wenzla** [comment]
Wait sorry nvm it seems to be in standard python

**Comment by wenzla** [comment]
I think we are done with this issue as I cleaned up the parser file and it is easily adjustable for different files and tags.
